// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGI9Y4eM0YqcRlixIBAYNDmC7DPrVWXHA',
    appId: '1:213240110149:web:178a8ff9d6b92650da972c',
    messagingSenderId: '213240110149',
    projectId: 'firefire-2313123123',
    authDomain: 'firefire-2313123123.firebaseapp.com',
    storageBucket: 'firefire-2313123123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIlHBeiSXZKp_LlJU4HUPncePXfAxGBk8',
    appId: '1:213240110149:android:63160af3fe95d58fda972c',
    messagingSenderId: '213240110149',
    projectId: 'firefire-2313123123',
    storageBucket: 'firefire-2313123123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIjN2zpCNj8_NdEnU-FzA8bDyQ_C2vJhw',
    appId: '1:213240110149:ios:ff831873cdabf05cda972c',
    messagingSenderId: '213240110149',
    projectId: 'firefire-2313123123',
    storageBucket: 'firefire-2313123123.appspot.com',
    iosClientId: '213240110149-snn57gu2h5do45v5ep8ud8c9c7dskvg1.apps.googleusercontent.com',
    iosBundleId: 'com.firebasefirebase.firefire',
  );
}
